// Generated by CoffeeScript 1.8.0
(function() {
  var eBookApp;

  eBookApp = angular.module('EbookApp', []);

  eBookApp.controller('MainCtrl', function($scope, $http, Ebook) {
    return $scope.onChange = function() {
      return Ebook.getJSON($scope.search).then(function(data) {
        if (data.responseStatus === 200) {
          return $scope.res = data.responseData.feed.entries;
        }
      });
    };
  });

  eBookApp.factory('Ebook', function($http, $q) {
    var Ebook;
    Ebook = (function() {
      function Ebook() {}

      Ebook.prototype.getJSON = function(word) {
        var $uri, config, deferred;
        deferred = $q.defer();
        $uri = "http://ajax.googleapis.com/ajax/services/feed/load?&v=1.0&output=json&callback=JSON_CALLBACK&num=40&q=" + encodeURIComponent("http://hon.jp/rest/2.1/" + word + "/ehonsearch/xslt=http://hon.jp/csv/rest_xslsample/sample_20_rss2.xsl&max=20");
        config = {
          params: {
            timeout: 10000
          }
        };
        $http.jsonp($uri, config).success(function(data) {
          return deferred.resolve(data);
        });
        return deferred.promise;
      };

      return Ebook;

    })();
    return new Ebook();
  });

}).call(this);
